/*  Problem 2: Even Fibonacci Numbers

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms. */

function fiboEvenSum(n) {
  let series = [1, 1]
  let sum = 0
  for (let i = 1; i <= n; i++) {
    let pos = series[i] + series[i - 1]
    pos % 2 === 0 ? sum += pos : 0
    series.push(pos)
  }

  return sum;
}

fiboEvenSum(10);